//Each new term in the Fibonacci sequence is generated by adding the previous two
//terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed 
//four million, find the sum of the even-valued terms.

#include <iostream>

int main()
{
    int num1 = 0;
    int num2 = 1;
    int sum = 0;
    while (num2 < 4000000)
    {
        int tmp = num2;
        num2 = num1 +num2;
        num1 = tmp;
        if (num2 % 2 == 0)
        {
            sum = num2 + sum;
        }
    }
    std::cout << "Fibonacci is the sum of even numbers: " << sum << std::endl;
}